android/app/src/main/AndroidManifest.xml
lib/pages/dialer/dialer.dart
lib/utils/voip_plugin.dart
lib/widgets/fluffy_chat_app.dart

Fixes #1164 , some of #963
Can now call consistently between Element Web and FluffyChat Android.

Fix call dialog on Android 11 + screen sharing 

---

lib/pages/chat/events/html_message.dart

I think it is a wrong fix for link, '\n' should not be replaceAll, so I think this should be reverted

fix: code cannot be wrap

---

assets/l10n/intl_en.arb
lib/config/app_config.dart
lib/config/setting_keys.dart
lib/pages/chat/chat.dart
lib/pages/settings_chat/settings_chat_view.dart
lib/widgets/matrix.dart

feat: option to not send typing notifications

---

lib/pages/chat/events/message.dart

It is the widget most often built, so every small bit helps.
- replace a List with an array (should be easier to optimize for the compiler)
- remove a Padding widget and use the parent Container's padding instead

small performance tweaks for Message

---

pubspec.lock

Fixed display name computation for direct chats on Conduit, a feature very relevant for me 🥺 ...

chore: bump matrix sdk

---

lib/main.dart

This adds a background fetch
mode on android which makes
sure that the flutter engine
is not rendered when the app
started to process background
push notifications only. This should
safe some resources like
battery and performance and
should make processing
background notifications
faster.

feat: Background fetch mode on Android

---

assets/l10n/intl_en.arb
lib/pages/chat/chat_emoji_picker.dart

Fixes #504 by using `emoji_picker_flutter`'s new features: customizable color scheme (which was not implemented when I introduced GitLab MR !1051 back then)
Before:
After:
Considering that there are multiple PRs related to emotes and emojis, I have reviewed that this PR:
+ **May likely to conflict with:**
- #1: PR completely replaces the default emoji picker design, but this PR may be merged as an existing workaround to #504
- #454: PR possibly triyng to fix GitLab issue !401, but introduces `noRecentEmojis` on l10n data (which this PR prefers `emoteKeyboardNoRecents` instead) with similar purpose, also converted `ChatEmojiPicker` into a `StatefulWidget`
* My PR can be closed to favor #454's implementation (just add the necessary color theme settings), but it may also conflict with #1's …

feat: Dynamic theming for emoji keyboard

---

Dockerfile

Related to #451, but about canvaskit instead of fonts.
Sources:
- https://github.com/flutter/flutter/issues/118473
- https://github.com/flutter/engine/blob/7b2db6dbe1c49a8004ff865607988eec36868ccc/lib/web_ui/lib/src/engine/canvaskit/initialization.dart#L51

Use locally hosted canvaskit instead of calling google

---

lib/pages/user_bottom_sheet/user_bottom_sheet.dart

fixes #644 
The following code is causing the issue:
It only pops `UserBottomSheet`, and leaves the `LoadProfileBottomSheet` to access the stale `outerContext` even after navigation is done.
```
case UserBottomSheetAction.message:
//more code
widget.outerContext.go('/rooms/${roomIdResult.result!}');
Navigator.of(context, rootNavigator: false).pop();
break;
```

fix: LoadProfileBottomSheet accessing disposed outerContext

---

Dockerfile

It seems jq is now required by the prepare-web.sh script, so add it in the builder image.

Fix Dockerfile: install jq in the builder image

---

README.md

Seems like it was removed from the MSC repo at some point.

Change dead link in README

---

Dockerfile

Fix dependency. missing yq when invoking setup-web. also ensure updated config.json copied
Current Docker file will error:
```
[+] Building 13.0s (12/16)
=> [internal] load build definition from Dockerfile                                                                                                                                                                                                                      0.0s
=> => transferring dockerfile: 429B                                                                                                                                                                                                                                      0.0s
=> [internal] load .dockerignore …
```

Fix: Fockerfile, yq dependency in scripts/prepare-web.sh

---

.github/workflows/release.yaml

This adds a new job to the release pipeline that builds and publishes the Docker image to the GitHub container registry. Example of it running in my fork: https://github.com/jgkawell/fluffychat/pkgs/container/fluffychat
This will help all of us who run the web version in Docker so that we can simply update the tag on our deployment manifest and grab the latest.

Added Docker deploy step to release

---

assets/l10n/intl_en.arb
lib/config/app_config.dart
lib/config/setting_keys.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_body.dart
lib/pages/settings_style/settings_style_view.dart
lib/widgets/matrix.dart

895de76e70466616d1baa45f21fa0a3fdeb30ec7 replaced the stories feature with presence status messages. Stories were an optional feature but right now presence information can only be disabled on a homeserver level.
Introduce a setting to make this feature optional on a client level.

feat: make showing user presence info optional

---

lib/pages/chat_list/chat_list_header.dart

If any selected room is not marked unread
(anySelectedRoomNotMarkedUnread), then show the 'mark unread' action
icon, else show the 'mark as read' icon.
This makes it consistent with the notification on/off action.
Similarly to the read/unread toggle this was also using the wrong icon.
If any selected room is not favourite, then show the pin icon (which
should represent the "mark as favourite" action as it corresponds to the
filled pin shown next to a favourited room. Otherwise show the outline
icon, representing the "unpin" action.

Fix swapped icons for mark read/unread and pin/unpin

---

lib/widgets/matrix.dart

This setting was not applied on app restart but always initialized to the default value. The only way change this was to go into settings and change the toggle twice after an app restart.

fix: properly initialize hideUnimportantStateEvents setting

---

lib/pages/homeserver_picker/homeserver_picker.dart

The path is just /auth.html in the docker image, not sure if its a different path for other installation methods

Point to correct path for auth.html so completing sso login flow no longer 404s

---

lib/utils/adaptive_bottom_sheet.dart

I realized for a while ago : If I login with a new session to FluffyChat, there always appears the friendly dialog asking me to perform SAS verification or SSSS unlock.
When on Linux, pressing the SAS button always failed. On mobile it worked. Looks like there was accidentally the root navigator used on desktops - and `Matrix.of(context)` (or whatever custom.of(context)) was unavailable in bottom sheets.
This PR fixes this bug by simply also not using the root navigator on desktops - as we already do on mobile. Disadvantage : If the `showModalBottomSheet` function is called from a sub-page on, it is only centered to that page. I guess that's definitely design wise a disadvantage but unless there's a better fix, I'd consider this as acceptable UI regression compared to have UI-wise …

fix: never use root navigator for bottom sheets

---

linux/CMakeLists.txt
pubspec.lock
pubspec.yaml

I close this option, to make it compilable on archlinux.
see the readme
https://github.com/simolus3/sqlite3.dart/blob/main/sqlcipher_flutter_libs/README.md
I do not think the option is needed  on linux machine

chore: do not use static openssl

---

assets/l10n/intl_en.arb
lib/config/app_config.dart
lib/config/setting_keys.dart
lib/pages/chat/events/message.dart
lib/pages/settings_chat/settings_chat_view.dart
lib/widgets/matrix.dart

I'd really love there to be an option to reply by swiping from left to right. So I added a small pull request with the corresponding changes.
There is now an option to change the swipe direction in the settings.
:white_check_mark: Tested on Android
Issues that "kinda" reference this: #891 and #957

feat: add option to configure reply swipe direction

---

lib/utils/background_push.dart
lib/utils/push_helper.dart

refactor: Reuse flutter local notifications object

---

lib/pages/chat_list/chat_list.dart
lib/pages/settings_security/settings_security.dart
lib/widgets/fluffy_chat_app.dart
lib/widgets/matrix.dart

refactor: Remove duplicated navigator workaround

---

lib/pages/chat/events/html_message.dart
lib/pages/chat/events/message_reactions.dart
lib/pages/chat/input_bar.dart
lib/pages/chat/sticker_picker_dialog.dart
lib/pages/settings_emotes/settings_emotes_view.dart

In this pull request I went over places where `MxcImage` is used and in case of custom emojis set `isThumbnail` to false, as the thumbnail generation causes emoticons to lose transparency and in some cases overall animations. (more info in #1071)
The only place I'm worried about is `html_message.dart`, where I'm using the following snippet: `isThumbnail: (actualWidth * actualHeight) > (256 * 256)`. Maybe using something the `data-mx-emoticon` property would be more fitting?
Fixes #1071
- [ ] Android
- [ ] iOS

fix: dont use thumbnails for emoticons

---

README.md

I also checked the famedly.com link and there's no product like server hosting at all for end-users (it's for medicinal staff), but I left it in :)

chore: Update Mastodon Link in README.md

---

lib/config/routes.dart

Changing the PageBuilder here based on a MediaQuery causes the child to briefly be rendered twice with the same GlobalKey, blowing up the rendering.
I believe this fixes https://github.com/krille-chan/fluffychat/issues/1534.
- [ ] iOS

fix: never use a transition on the shell route

---

lib/pages/new_group/new_group.dart

- [ ] Android
- [ ] iOS
Hello! This PR is related to issue #1602 
I'm not sure if the option to create rooms without names is there on purpose (if it is, please let me know), but it can be a confusing user experience. This PR prevents …

fix: prevent users from creating group chats or spaces with empty names

---

lib/pages/login/login_view.dart

Fixes the element padding between server picker and login view to be consistent with each other. `LoginView` has padding 8.0 while `HomeserverPickerView` has 32.0. This PR adjusts the `LoginView` padding to be 8+24 = 32 for consistent look.
- [ ] iOS

fix: Consistent element padding between server picker and login view

---

lib/utils/file_selector.dart

(I think this) Fixes https://github.com/krille-chan/fluffychat/issues/1667
I cannot use the tools for building, testing and automatically formatting this, so feel free to directly edit this PR, if necessary.

Make more file-types visible when selecting images or videos to send

---

lib/pages/chat/chat.dart

Before, if the user typed too many lines it would overflow past the input box and also leave a very long message in chat. Now, it is limited and won't expand in the input box past 4 lines. This fixes #2066 
- [ ] Android
- [ ] iOS …

fix: limit characters and lines so redact message can't be too long
