krille-chan/fluffychat

lib/pages/chat_list/chat_list_item.dart
- extract hasNotifications to a variable
this is more clear and potentially faster as we don't compute `notifications > 0` multiple times
- make a text style const
=> feat/ChatListItem: small changes

android/app/src/main/AndroidManifest.xml
=> chore: added android audio sharing intent

lib/pages/chat/events/video_player.dart
=> fix: navigating back from full screen video

lib/config/app_config.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart, lib/pages/settings_chat/settings_chat_view.dart
closes https://github.com/krille-chan/fluffychat/issues/711
=> fix: Cannot change send on enter on desktop

assets/l10n/intl_en.arb, lib/config/routes.dart, lib/pages/settings_password/settings_password.dart, lib/pages/settings_password/settings_password_view.dart, lib/pages/settings_security/settings_security.dart, lib/pages/settings_security/settings_security_view.dart, lib/utils/localized_exception_extension.dart
closes https://github.com/krille-chan/fluffychat/issues/707
closes https://github.com/krille-chan/fluffychat/issues/663
=> feat: New change password page with server capabilities check

lib/widgets/public_room_bottom_sheet.dart
closes https://github.com/krille-chan/fluffychat/issues/662
=> fix: Join public rooms

lib/pages/user_bottom_sheet/user_bottom_sheet.dart
closes https://github.com/krille-chan/fluffychat/issues/656
=> fix: Make user admin

lib/config/routes.dart, lib/pages/chat/chat.dart, lib/pages/chat_list/chat_list_item.dart
Fixes https://github.com/krille-chan/fluffychat/issues/760
=> refactor: Put forwarded text into inputfield instead of sending directly

lib/pages/chat/send_file_dialog.dart
Enhance send video functionality by adding a toggle button "send_original" on file upload dialogbox. 
Issue reference link : https://github.com/krille-chan/fluffychat/issues/812
=> enhanced send video functionality by adding toggle send original

pubspec.lock, pubspec.yaml, scripts/enable-android-google-services.patch
=> build: Update dependencies after release

scripts/prepare-web.sh
=> fix: little issues in `prepare-web` script

lib/pages/settings_emotes/settings_emotes.dart, lib/utils/client_download_content_extension.dart, lib/utils/push_helper.dart, lib/widgets/local_notifications_extension.dart, lib/widgets/mxc_image.dart, pubspec.lock, pubspec.yaml
=> feat: Use matrix authenticated media

scripts/prepare-web.sh
Reverts krille-chan/fluffychat#1297
Unfortunately breaks the build web ci
=> Revert "fix: little issues in `prepare-web` script"

linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, linux/my_application.cc, pubspec.lock, pubspec.yaml, snap/snapcraft.yaml
To be merged after https://github.com/krille-chan/fluffychat/pull/1269
=> build: Fix build linux after flutter 3.24.1 and add handy_window

lib/pages/chat/chat.dart
We do our own image compression in the dark sdk anyway.
Might fix #1168
- [ ] Android
- [ ] iOS
=> fix: Bypass image compression in flutter_file_picker

pubspec.lock, pubspec.yaml
=> build: Update to matrix dart sdk 0.33

lib/utils/background_push.dart, pubspec.lock
=> build: Update dependencies

lib/utils/background_push.dart, pubspec.lock, pubspec.yaml
Add unifiedpush_ui as a part of unifiedpush was split off into it.
- [ ] (Not applicable) Every new feature or change of the design/GUI is linked to an approved design proposal in an issue
- [ ] (Not applicable) Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every release, e.g. a volunteer who takes over maintainership
- [ ] iOS
=> build: Add unifiedpush_ui package

lib/pages/chat/chat.dart, lib/pages/chat_details/chat_details.dart, lib/pages/homeserver_picker/homeserver_picker.dart, lib/pages/new_group/new_group.dart, lib/pages/new_space/new_space.dart, lib/pages/settings/settings.dart, lib/pages/settings_emotes/settings_emotes.dart, lib/pages/settings_style/settings_style.dart, lib/utils/file_selector.dart, pubspec.lock, pubspec.yaml, scripts/enable-android-google-services.patch
=> refactor: Use file selector on linux

pubspec.lock, pubspec.yaml
=> build: Update dependencies minor versions

lib/config/routes.dart, lib/pages/chat/chat.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/image_viewer/image_viewer.dart, lib/utils/show_scaffold_dialog.dart, lib/widgets/matrix.dart, lib/widgets/share_scaffold_dialog.dart
=> refactor: Improved share / forward dialog

android/app/src/main/AndroidManifest.xml, ios/FluffyChat Share/Info.plist
=> chore: Enable share multiple files to app

lib/pages/chat_access_settings/chat_access_settings_page.dart, lib/utils/adaptive_bottom_sheet.dart
=> build: Make import sorter check not fail

lib/pages/chat_details/chat_details_view.dart, lib/pages/new_private_chat/new_private_chat_view.dart, lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart, lib/widgets/public_room_bottom_sheet.dart, lib/widgets/qr_code_viewer.dart, pubspec.lock, pubspec.yaml
=> feat: QR Code viewer for mxid sharing

macos/Podfile.lock, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/AppDelegate.swift
This commit was generated mostly by running `flutter run -d macos` and then `pod update` in the `macos/` directory after that failed.
- [ ] Android
- [ ] iOS
=> fix(macos): update dependencies to make the build work

android/app/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, scripts/enable-android-google-services.patch
Reverts krille-chan/fluffychat#1674
=> Revert "build: Update kotlin gradle plugin"

assets/l10n/intl_en.arb, lib/pages/chat/command_hints.dart, pubspec.lock, pubspec.yaml
=> build: Update openssl to 0.5.0

pubspec.lock, pubspec.yaml
=> build: Update local notifications and gorouter package

lib/config/setting_keys.dart, lib/pages/chat/chat.dart, lib/pages/settings_security/settings_security.dart, lib/utils/client_manager.dart, lib/utils/matrix_sdk_extensions/flutter_matrix_dart_sdk_database/cipher.dart
=> refactor: Migrate more config options to config viewer

lib/widgets/public_room_bottom_sheet.dart, pubspec.lock, pubspec.yaml
=> build: Update matrix dart sdk to 0.39.0

lib/pages/chat/chat_app_bar_list_tile.dart, lib/pages/chat/events/audio_player.dart, lib/pages/chat/events/image_bubble.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/message_download_content.dart, lib/pages/chat/events/video_player.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_search/chat_search_message_tab.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/settings_homeserver/settings_homeserver_view.dart, lib/widgets/adaptive_dialogs/public_room_dialog.dart, lib/widgets/adaptive_dialogs/show_ok_cancel_alert_dialog.dart, lib/widgets/adaptive_dialogs/show_text_input_dialog.dart, lib/widgets/adaptive_dialogs/user_dialog.dart
closes https://github.com/krille-chan/fluffychat/issues/488
- [ ] iOS
- [ ] …
=> fix: Text scale factor in Linkify widgets

CHANGELOG.md
before this, most of the changes appeared to have been taken back 🥴
- [ ] Android
- [ ] iOS
=> fix(docs): escape tag

lib/widgets/local_notifications_extension.dart
try to support avarar icon
Seems something wrong with the data of the image..
- [ ] Android
- [ ] iOS
- [ ] Browser …
=> feat(linux/notify): support avarar icon on notification

lib/pages/chat/events/message_download_content.dart
- [ ] Android
- [ ] iOS
Closes: #2031
=> fix: Add flexible to file messages to prevent long name overflow

lib/utils/matrix_sdk_extensions/flutter_matrix_dart_sdk_database/builder.dart
Fixes #2018
I think it needs testing on other platforms too.
- [ ] iOS
=> fix: Create a subdirectory in the tmp directory

android/app/build.gradle.kts, pubspec.lock
=> build: Update flutter sdk and ndk
